post http://localhost:3000/invite-employee
Content-Type: application/json

{
    "email": "anthonyvidovic@gmail.com",
    "signUpCode": "12345"
}

###

GET http://localhost:3000/overview

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "av@gmail.com",
    "password": "asdasdasd"
}

###
curl https://api.goshippo.com/tracks/fedex/281729605885 \
    -H "Authorization: ShippoToken shippo_live_d94c55abdf656717365c634cf8182c5f5986c3db"


    //shippo_live_d94c55abdf656717365c634cf8182c5f5986c3db
